env:
  global:
    - CC_TEST_REPORTER_ID=f623122fc9db8ff7147d82f879a261b6e6391025ec1a6b3c14e48c0c11776aa0
language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
install:
- pip install -r requirements.txt
- pip install flake8
- python setup.py install
#deploy:
#  provider: pypi
#  user: __token__
#  password:
#    secure: <token goes here>
#  distributions: sdist bdist_wheel bdist_egg
#  skip_existing: true
#  on:
#    branch: master
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- flake8 src/pypure
- echo "Done"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
